//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 04:40:19 PM MSK 
//


package com.senchenko.devices.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="is-peripheral" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="power-usage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="with-cooler" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="component-group" type="{http://www.example.com/devices}TypeDevice"/>
 *       &lt;/sequence>
 *       &lt;attribute name="port-type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="USB"/>
 *             &lt;enumeration value="LPT"/>
 *             &lt;enumeration value="COM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type", propOrder = {
    "isPeripheral",
    "powerUsage",
    "withCooler",
    "componentGroup"
})
public class Type {

    @XmlElement(name = "is-peripheral")
    protected boolean isPeripheral;
    @XmlElement(name = "power-usage", required = true)
    protected String powerUsage;
    @XmlElement(name = "with-cooler")
    protected boolean withCooler;
    @XmlElement(name = "component-group", required = true)
    @XmlSchemaType(name = "string")
    protected TypeDevice componentGroup;
    @XmlAttribute(name = "port-type")
    protected String portType;

    /**
     * Gets the value of the isPeripheral property.
     * 
     */
    public boolean isIsPeripheral() {
        return isPeripheral;
    }

    /**
     * Sets the value of the isPeripheral property.
     * 
     */
    public void setIsPeripheral(boolean value) {
        this.isPeripheral = value;
    }

    /**
     * Gets the value of the powerUsage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerUsage() {
        return powerUsage;
    }

    /**
     * Sets the value of the powerUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerUsage(String value) {
        this.powerUsage = value;
    }

    /**
     * Gets the value of the withCooler property.
     * 
     */
    public boolean isWithCooler() {
        return withCooler;
    }

    /**
     * Sets the value of the withCooler property.
     * 
     */
    public void setWithCooler(boolean value) {
        this.withCooler = value;
    }

    /**
     * Gets the value of the componentGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDevice }
     *     
     */
    public TypeDevice getComponentGroup() {
        return componentGroup;
    }

    /**
     * Sets the value of the componentGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDevice }
     *     
     */
    public void setComponentGroup(TypeDevice value) {
        this.componentGroup = value;
    }

    /**
     * Gets the value of the portType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortType() {
        return portType;
    }

    /**
     * Sets the value of the portType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortType(String value) {
        this.portType = value;
    }

}
